In [10]:
# Kyuho Lee, Problem Set 2
# Start with importing package
import numpy as np

In [11]:
# Given Matrices A, B, and C
Al = [[0.33635, 0.14270, 0.42717], [0.58224, 0.39448, 0.20009], [0.97568, 0.47800, 0.24646]]
Bl = [[0.244870, 0.297137, 0.588115, 0.309824],[0.674382, 0.716121, 0.037115, 0.318450],
     [0.620510, 0.927583, 0.415386, 0.231517], [0.914291, 0.518357, 0.146571, 0.245268]]
Cl = [[0.410958, 0.881281, 0.841645, 0.653753, 0.062568],[0.328874, 0.390312, 0.242873, 0.460719, 0.119437],
    [0.415604, 0.228442, 0.101438, 0.210469, 0.914524], [0.609891, 0.103584, 0.254734, 0.181744, 0.831333],
    [0.461681, 0.690882, 0.481377, 0.382639, 0.730652]]
type(Al)

# convert lists into matrices
A = np.mat(Al)
B = np.mat(Bl)
C= np.mat(Cl)
# Print matrices to check typos
print("Matrix A: \n", A)
print("Matrix B: \n", B)
print("Matrix B: \n", C)

Matrix A: 
 [[0.33635 0.1427  0.42717]
 [0.58224 0.39448 0.20009]
 [0.97568 0.478   0.24646]]
Matrix B: 
 [[0.24487  0.297137 0.588115 0.309824]
 [0.674382 0.716121 0.037115 0.31845 ]
 [0.62051  0.927583 0.415386 0.231517]
 [0.914291 0.518357 0.146571 0.245268]]
Matrix B: 
 [[0.410958 0.881281 0.841645 0.653753 0.062568]
 [0.328874 0.390312 0.242873 0.460719 0.119437]
 [0.415604 0.228442 0.101438 0.210469 0.914524]
 [0.609891 0.103584 0.254734 0.181744 0.831333]
 [0.461681 0.690882 0.481377 0.382639 0.730652]]


In [12]:
# In-built Function to check eigenvalue and eigenvector
e_a, v_a = np.linalg.eig(A)
e_b, v_b = np.linalg.eig(B)
e_c, v_c = np.linalg.eig(C)
print("Used in-built function for checking answer purpose, matrix A \n", "eigenvalue :", 
      e_a[0], "\n", "eigenvector :\n", v_a[:,0])
print("Used in-built function for checking answer purpose, matrix B \n", "eigenvalue :", 
      e_b[0], "\n", "eigenvector :\n", v_b[:,0])
print("Used in-built function for checking answer purpose, matrix C \n", "eigenvalue :", 
      e_c[0], "\n", "eigenvector :\n", v_c[:,0])

Used in-built function for checking answer purpose, matrix A 
 eigenvalue : 1.1885258909973506 
 eigenvector :
 [[-0.45152677]
 [-0.51473751]
 [-0.72881333]]
Used in-built function for checking answer purpose, matrix B 
 eigenvalue : (1.7369922251725654+0j) 
 eigenvector :
 [[-0.43146497+0.j]
 [-0.45793804+0.j]
 [-0.60866465+0.j]
 [-0.48338191+0.j]]
Used in-built function for checking answer purpose, matrix C 
 eigenvalue : (2.2176964334313167+0j) 
 eigenvector :
 [[0.51126449+0.j]
 [0.29262727+0.j]
 [0.40925311+0.j]
 [0.43988999+0.j]
 [0.54035784+0.j]]


In [14]:
# Define power iteration
def poweriter(mtx, x, l = 1, tol = 1e-8, maxit = 100, verbose=False):
    for i in range(maxit):
        i = i + 1 # Count iternation
        u = x / np.linalg.norm(x) # Normalize x to prevent explosion
        x = mtx * u # update x vector
        l = u.T * x # lambda eigenvalue
        if np.linalg.norm(mtx * x - x * l) <= tol:
            return x, l, i
        x = x / l
        if(verbose):
            print("Iteration time:",i, "lambda:",l, "\n x=",x)
    print("Max iterations.")
    return(none)

In [15]:
# Assign random x vectors
rd = np.random.RandomState(888) 
x_a = rd.random((3, 1)) # Random vector for matrix A
x_b = rd.random((4, 1)) # Random vector for matrix B
x_c = rd.random((5, 1)) # Random vector for matrix C

In [16]:
# Run Poweriteration
m_a = poweriter(A, x_a) # Matrix A
m_b = poweriter(B, x_b) # Matrix B
m_c = poweriter(C, x_c) # Matrix C

print("After", m_a[2], "iterations Matrix A's eigenvalue and eigenvector\n", 
     "eigenvalue :\n", m_a[1], "\n eigenvector : \n", m_a[0])
print("After", m_b[2], "iterations Matrix B's eigenvalue and eigenvector\n", 
     "eigenvalue :\n", m_b[1], "\n eigenvector : \n", m_b[0])
print("After", m_c[2], "iterations Matrix C's eigenvalue and eigenvector\n", 
     "eigenvalue :\n", m_c[1], "\n eigenvector : \n", m_c[0])

After 15 iterations Matrix A's eigenvalue and eigenvector
 eigenvalue :
 [[1.18852589]] 
 eigenvector : 
 [[0.53665126]
 [0.61177886]
 [0.86621351]]
After 12 iterations Matrix B's eigenvalue and eigenvector
 eigenvalue :
 [[1.73699222]] 
 eigenvector : 
 [[0.74945129]
 [0.79543481]
 [1.05724577]
 [0.83963062]]
After 11 iterations Matrix C's eigenvalue and eigenvector
 eigenvalue :
 [[2.21769643]] 
 eigenvector : 
 [[1.13382943]
 [0.64895846]
 [0.90759916]
 [0.97554246]
 [1.19834965]]
